---
title: "Innovation Amidst Covid-19"
description: |
  A Visual Analytics Project for ISSS608
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

```



Covid-19’s impacts on workers and workplaces across the globe has been dramatic. Indeed, there will be global business realignment triggered by the global Covid-19 pandemic disruptions.
In this project, we analyse and identify patterns regarding the Global Innovation Score comparing pre-and post Covid-19 pandemic in different countries based on the Global Innovation Index 2020 and specifically to better understand the impact in Singapore.

Our approach includes developing a R-Shiny application for an interactive:

(1) Exploratory Data Analysis which includes a **Choropleth Map**, **Bubble Plot**, **Visualising Uncertainty**, and **Time-series Analysis**, and 
(2) Statistical Analysis which includes **Correlation Analysis**, **Multiple Linear Regression Model**, and **Hierarchical Clustering**.





